artifacts_root: artifacts_root

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://huggingface.co/datasets/AnsariSahil/OCR_datset
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "val"]  

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/dataset_new
  model: microsoft/layoutlmv3-base


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_preprocessing/encoded_data
  model: microsoft/layoutlmv3-base

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/trained-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv  